name: Android CI Build APK

on:
  push:
    branches: [ main ] # Assuming 'main' is the default branch
  pull_request:
    branches: [ main ] # Assuming 'main' is the default branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'gradle' # Cache Gradle dependencies based on setup-java documentation

      # Optional: Explicit Gradle Caching (setup-java with cache: 'gradle' might handle this)
      # - name: Cache Gradle packages
      #   uses: actions/cache@v3
      #   with:
      #     path: |
      #       ~/.gradle/caches
      #       ~/.gradle/wrapper
      #     key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
      #     restore-keys: |
      #       ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle (Debug APK)
        run: ./gradlew assembleDebug # This will build the debug APK for the 'app' module by default

      - name: Upload Debug APK
        uses: actions/upload-artifact@v3
        with:
          name: app-debug # Name of the artifact bundle
          path: app/build/outputs/apk/debug/app-debug.apk # Path to the APK
          if-no-files-found: error # Optional: fail the step if the APK is not found
