package com.joaomgcd.taskerpluginlibrary

object TaskerPluginConstants {
    const val TASKER_MESSAGE_RESPONSE_ACTION_ID_KEY = "actionId"
    const val TASKER_MESSAGE_RESPONSE_ERROR_KEY = "error"
    const val TASKER_MESSAGE_RESPONSE_ERROR_CODE_KEY = "errorCode"
    const val TASKER_MESSAGE_RESPONSE_ERROR_MESSAGE_KEY = "errorMessage"
    const val TASKER_MESSAGE_RESPONSE_REPLACE_VARIABLES_KEY = "replaceVariables"
    const val TASKER_MESSAGE_RESPONSE_VARIABLES_KEY = "variables"
    const val IsTaskerMessage = "IsTaskerMessage"
    const val ACTION_EXECUTE_PLUGIN = "com.joaomgcd.taskerpluginlibrary.ACTION_EXECUTE_PLUGIN"
    const val EXTRA_INPUT = "com.joaomgcd.taskerpluginlibrary.EXTRA_INPUT"
    const val EXTRA_CONFIG = "com.joaomgcd.taskerpluginlibrary.EXTRA_CONFIG"
    const val EXTRA_REQUEST_TYPE = "com.joaomgcd.taskerpluginlibrary.EXTRA_REQUEST_TYPE"
    const val EXTRA_ACTIVITY_CONFIG = "com.joaomgcd.taskerpluginlibrary.EXTRA_ACTIVITY_CONFIG"
    const val EXTRA_BUNDLE = "com.twofortyfouram.locale.intent.extra.BUNDLE"
    const val EXTRA_BLURB = "com.twofortyfouram.locale.intent.extra.BLURB"
    const val EXTRA_STRING_BLURB = EXTRA_BLURB // Old Tasker versions use this
    const val EXTRA_RELEVANT_VARIABLES = "net.dinglisch.android.tasker.extras.RELEVANT_VARIABLES"
    const val BUNDLE_KEY_INPUT_JSON = "input"
    const val BUNDLE_KEY_VERSION_CODE = "versionCode"
    const val BUNDLE_KEY_RUNNER_CLASS_NAME = "runnerClassName"
    const val BUNDLE_KEY_MINIMUM_TASKER_VERSION = "minimumTaskerVersion"
    const val BUNDLE_KEY_TARGET_TASKER_VERSION = "targetTaskerVersion"
    const val BUNDLE_KEY_ACTIVITY_FULL_CLASS_NAME = "activityFullName"
    const val BUNDLE_KEY_HELP_URL = "helpUrl"
    const val BUNDLE_KEY_REQUESTED_PERMISSIONS = "requestedPermissions"
    const val BUNDLE_KEY_PASS_THROUGH_DATA = "passThroughData"
    const val BUNDLE_KEY_VARIABLES_PREFIX = "variablesPrefix"

    const val DEFAULT_MINIMUM_TASKER_VERSION = "5.9.3"
    const val VARIABLE_TASKER_ERROR_CODE = "tasker_error_code"
    const val VARIABLE_TASKER_ERROR_MESSAGE = "tasker_error_message"
    const val RENAME_PREFIX = "tp_rename_"
    const val RENAME_SUFFIX = "_to"
    const val RENAME_CONFIG_SEPARATOR = "->"
    const val RENAME_CONFIG_VARIABLES_SEPARATOR = ","
}
