name: Setup Gradle Wrapper

on:
  workflow_dispatch: # permet de déclencher manuellement l'action

jobs:
  setup-wrapper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java 17 (compatible avec Gradle 8.4)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Generate Gradle Wrapper in TaskerCalendarPlugin
        run: gradle wrapper --gradle-version 8.4
        working-directory: ./TaskerCalendarPlugin

      - name: Upload generated wrapper files
        uses: actions/upload-artifact@v4
        with:
          name: gradle-wrapper
          path: |
            TaskerCalendarPlugin/gradlew
            TaskerCalendarPlugin/gradlew.bat
            TaskerCalendarPlugin/gradle/wrapper/gradle-wrapper.jar
            TaskerCalendarPlugin/gradle/wrapper/gradle-wrapper.properties
